function [k,Accuracy,Kappa,AccuracySD,KappaSD] = importcv(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [K,ACCURACY,KAPPA,ACCURACYSD,KAPPASD] = IMPORTFILE(FILENAME) Reads data
%   from text file FILENAME for the default selection.
%
%   [K,ACCURACY,KAPPA,ACCURACYSD,KAPPASD] = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [k,Accuracy,Kappa,AccuracySD,KappaSD] = importfile('cv-2-1-100-0.2-10.csv',2, 12);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/02/23 12:10:54

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column2: double (%f)
%	column3: double (%f)
%   column4: double (%f)
%	column5: double (%f)
%   column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*q%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
k = dataArray{:, 1};
Accuracy = dataArray{:, 2};
Kappa = dataArray{:, 3};
AccuracySD = dataArray{:, 4};
KappaSD = dataArray{:, 5};


